name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Atualizado para a versão mais recente
      - name: Update README with recent GitHub activity
        uses: jamesgeorge007/github-activity-readme@master # Verifique por atualizações
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
