name: Update README
on:
  schedule:
    - cron: "*/0 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: c3t4r4
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update README with the recent activity"
          MAX_LINES: 4
          COMMIT_NAME: GitHub Activity Readme
